theme = "hugo-tailwindcss-starter-theme"
languageCode = "en-us"
baseurl = "/"
title = "Hugo Tailwindcss Starter"
ignoreFiles = [ "\\.qmd$", "\\.ipynb$", "\\.py$" ]

author = "Dirk Olbrich"
copyright = "Copyright © 2019-2023, Dirk Olbrich, all rights reserved."

[params]
    name = "Hugo Tailwindcss Starter"
    description = "A simple bootstraped theme for Hugo, build with Tailwindcss."

    github_user = "dirkolbrich"
    github_repo = "https://github.com/dirkolbrich/hugo-tailwindcss-starter-theme"
    github_banner = true

    favicon = "favicon.ico"

# syntax highlight settings
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    # one of: https://xyproto.github.io/splash/docs/ 
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
    hardwraps = false 
